version: '3.8'

services:
  order-service:
    build:
      context: ./order_service
    container_name: order-service
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/orders_db
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/

  payment-service:
    build:
      context: ./payment_service
    container_name: payment-service
    ports:
      - "8002:8002"
    depends_on:
      - rabbitmq
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/

  notification-service:
    build:
      context: ./notification_service
    container_name: notification-service
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
